#!/usr/bin/perl
#
# brabo
#

use Modern::Perl;
use Net::DNS;

my $type = "ANY";

my $domain = "isc.org";

my $a = 4;
my $b = 2;
my $c = 2;
my $k = 0;

my $z = 10;
my $x = 1;
while ($c < 9 ) {
		my @childs;
	        $z = 254;

		for ( my $i = 0; $i < $z; $i++ ) {
			my $pid = fork();
			if ($pid) {
				#parent
				push(@childs, $pid);
			} elsif ($pid == 0) {
				my $y = $x + $i;
				my $dns = "$a.$b.$c.$y";

				my $resolver   = Net::DNS::Resolver->new(
					nameservers => [ $dns ],
					recurse     => 1,
					debug       => 0,
					retry       => 1,
				);

				$resolver->tcp_timeout(0.2);

				$resolver->udp_timeout(0.2);
				my $result = $resolver->query($domain, $type);

				if ($result) {
					print "$dns OPEN\n";
				} else {
					exit 0;
				}

				exit 0;
			}
		}
		foreach (@childs) {
			waitpid($_, 0);
		}
	$x = 1;
	$c++;
}
