#!/usr/bin/perl

use Modern::Perl;

use Net::DNS;

my $type = "PTR";

my $server_list = 'dnsservers';
open(SERVERLST, $server_list) || warn ("Failed to open server list $server_list - $!");


my @available_servers;
my @answer_list;
my @t;

for my $line (<SERVERLST>) {
	next if $line =~ /^(#|$)/;
	my %data;

	@data{qw(ip host note)} = split /\s+/, $line, 3;
	push @available_servers, {%data};
}
close SERVERLST;

my $a = 195;
my $b = 67;
my $c = 212;
my $d = 19;

print "\n";

#my $server = ((sort { (-1,1)[rand 2] } @available_servers)[1]);
my $server;

#for $server (@available_servers) {
my $len = $#available_servers + 1;
print $len;

#while ( $outer < 
